target 'RedBus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RedBus
  pod 'SwiftyJSON', '~> 3.1.3'
  pod 'Alamofire', '~> 4.7.2'
  pod 'SDWebImage', '~> 4.4.1'

end

target 'RedBusUnitTests' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for InfiniteScrollTests
    pod 'SwiftyJSON', '~> 3.1.3'
    pod 'Alamofire', '~> 4.7.2'
    pod 'SDWebImage', '~> 4.4.1'
    
end
