# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CricketNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CricketNews
  pod 'SwiftyJSON', '~> 3.1.3'
  pod 'Alamofire', '~> 4.7.2'
  pod 'SDWebImage', '~> 4.0'
  pod 'SwiftSpinner'

end

target 'CricketNewsUnitTests' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for CricketNewsUnitTests
    pod 'SwiftyJSON', '~> 3.1.3'
    pod 'Alamofire', '~> 4.7.2'
    pod 'SDWebImage', '~> 4.0'
    pod 'SwiftSpinner'
    
end
